// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRNr0tqz_ZUblivNWxKyfhDF4XOnxuQE',
    appId: '1:49892768737:web:dede83c9d71779bcc270a0',
    messagingSenderId: '49892768737',
    projectId: 'chat-app-f9d7c',
    authDomain: 'chat-app-f9d7c.firebaseapp.com',
    storageBucket: 'chat-app-f9d7c.appspot.com',
    measurementId: 'G-ZVTHK9304K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDDZkwGgP6av45QJe6tJKsl6lmwsx5Dk',
    appId: '1:49892768737:android:dba78eba39122041c270a0',
    messagingSenderId: '49892768737',
    projectId: 'chat-app-f9d7c',
    storageBucket: 'chat-app-f9d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMW07BhxHLFsIoXXkCxtdHV4ty-So5QoU',
    appId: '1:49892768737:ios:c941cfd498313c7dc270a0',
    messagingSenderId: '49892768737',
    projectId: 'chat-app-f9d7c',
    storageBucket: 'chat-app-f9d7c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMW07BhxHLFsIoXXkCxtdHV4ty-So5QoU',
    appId: '1:49892768737:ios:e9e4e2c25f7feea1c270a0',
    messagingSenderId: '49892768737',
    projectId: 'chat-app-f9d7c',
    storageBucket: 'chat-app-f9d7c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
